"""cikarim motoru: calistirmalar, gold set, kartlar, gommeler, llm onbellegi

SPRINT 3'ün çıkarım motorunun tüm şeması TEK GÖÇTE kurulur — SPRINT 3B'de
(yerel model kurulumu) ikinci bir Alembic başı doğmasın diye. `embeddings`
tablosu bu sprintte OLUŞTURULUR ama DOLDURULMAZ; doldurma SPRINT 5'tedir.

Eklenenler:
  - `extraction_runs`   — her çıkarım çalıştırmasının kipi ve sayaçları
  - `gold_annotations`  — insan cevap anahtarı (kör / ön-doldurmalı ayrımıyla)
  - `entity_cards`      — varlık kartları (gömmenin girdisi)
  - `embeddings`        — vektör gösterimleri (şema hazır, boş)
  - `llm_cache`         — model yanıtı önbelleği
  - `campaign_extractions.rejected_reason` — reddedilen çıkarımın gerekçesi

⚠️ `rejected_reason` NEDEN EKLENDİ: Halüsinasyon guard'ının reddettiği
çıkarımlar SİLİNMEZ, işaretlenerek saklanır. Silinseydi sistem kusursuz
görünür ve "bilgi yokken bilgi üretmeme" yeteneği — şartname 7'de puanlanan
madde — ölçülemez, yalnızca iddia edilebilirdi.

Revision ID: 0004
Revises: 0003
Create Date: 2026-08-16 10:49:47.945163
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '0004'
down_revision: str | None = '0003'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Şemayı ileri al."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('embeddings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.Text(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('chunk_text', sa.Text(), nullable=False),
    sa.Column('embedding', sa.LargeBinary(), nullable=False),
    sa.Column('dim', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.Text(), nullable=False),
    sa.Column('source_hash', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("entity_type IN ('campaign', 'product', 'product_rate', 'glossary', 'bank')", name=op.f('ck_embeddings_entity_type_valid')),
    sa.CheckConstraint('dim > 0', name=op.f('ck_embeddings_dim_positive')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_embeddings')),
    sa.UniqueConstraint('entity_type', 'entity_id', 'chunk_index', name='uq_embeddings_entity_type_entity_id_chunk_index')
    )
    with op.batch_alter_table('embeddings', schema=None) as batch_op:
        batch_op.create_index('ix_embeddings_model_name_entity_type', ['model_name', 'entity_type'], unique=False)

    op.create_table('entity_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.Text(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('card_text', sa.Text(), nullable=False),
    sa.Column('card_hash', sa.Text(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("entity_type IN ('campaign', 'product', 'product_rate', 'glossary', 'bank')", name=op.f('ck_entity_cards_entity_type_valid')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_entity_cards')),
    sa.UniqueConstraint('entity_type', 'entity_id', name='uq_entity_cards_entity_type_entity_id')
    )
    op.create_table('extraction_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mode', sa.Text(), nullable=False),
    sa.Column('scope', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('campaigns_processed', sa.Integer(), nullable=False),
    sa.Column('fields_extracted', sa.Integer(), nullable=False),
    sa.Column('fields_rejected', sa.Integer(), nullable=False),
    sa.Column('llm_calls', sa.Integer(), nullable=False),
    sa.Column('cache_hits', sa.Integer(), nullable=False),
    sa.Column('errors_count', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.Text(), nullable=True),
    sa.Column('prompt_version', sa.Text(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('error_log', sa.Text(), nullable=True),
    sa.CheckConstraint("mode IN ('hybrid', 'rule_only', 'llm_only')", name=op.f('ck_extraction_runs_mode_valid')),
    sa.CheckConstraint("status IN ('running', 'success', 'partial', 'failed', 'cancelled')", name=op.f('ck_extraction_runs_status_valid')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_extraction_runs'))
    )
    op.create_table('llm_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cache_key', sa.Text(), nullable=False),
    sa.Column('task', sa.Text(), nullable=False),
    sa.Column('response_json', sa.Text(), nullable=False),
    sa.Column('model_name', sa.Text(), nullable=False),
    sa.Column('prompt_version', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("task IN ('extract', 'classify', 'summarize')", name=op.f('ck_llm_cache_task_valid')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_llm_cache')),
    sa.UniqueConstraint('cache_key', name='uq_llm_cache_cache_key')
    )
    with op.batch_alter_table('llm_cache', schema=None) as batch_op:
        batch_op.create_index('ix_llm_cache_model_name_prompt_version', ['model_name', 'prompt_version'], unique=False)

    op.create_table('gold_annotations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('field_name', sa.Text(), nullable=False),
    sa.Column('gold_value', sa.Text(), nullable=True),
    sa.Column('unit', sa.Text(), nullable=True),
    sa.Column('evidence_text', sa.Text(), nullable=True),
    sa.Column('annotator', sa.Text(), nullable=False),
    sa.Column('method', sa.Text(), nullable=False),
    sa.Column('is_difficult', sa.Boolean(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("method IN ('blind', 'assisted')", name=op.f('ck_gold_annotations_method_valid')),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name=op.f('fk_gold_annotations_campaign_id_campaigns'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gold_annotations')),
    sa.UniqueConstraint('campaign_id', 'field_name', 'annotator', name='uq_gold_annotations_campaign_id_field_name')
    )
    with op.batch_alter_table('gold_annotations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gold_annotations_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_gold_annotations_field_name'), ['field_name'], unique=False)
        batch_op.create_index('ix_gold_annotations_method_is_difficult', ['method', 'is_difficult'], unique=False)

    with op.batch_alter_table('campaign_extractions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rejected_reason', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Şemayı geri al."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaign_extractions', schema=None) as batch_op:
        batch_op.drop_column('rejected_reason')

    with op.batch_alter_table('gold_annotations', schema=None) as batch_op:
        batch_op.drop_index('ix_gold_annotations_method_is_difficult')
        batch_op.drop_index(batch_op.f('ix_gold_annotations_field_name'))
        batch_op.drop_index(batch_op.f('ix_gold_annotations_campaign_id'))

    op.drop_table('gold_annotations')
    with op.batch_alter_table('llm_cache', schema=None) as batch_op:
        batch_op.drop_index('ix_llm_cache_model_name_prompt_version')

    op.drop_table('llm_cache')
    op.drop_table('extraction_runs')
    op.drop_table('entity_cards')
    with op.batch_alter_table('embeddings', schema=None) as batch_op:
        batch_op.drop_index('ix_embeddings_model_name_entity_type')

    op.drop_table('embeddings')
    # ### end Alembic commands ###
